openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8443
  description: Generated server url
paths:
  /api/users/{username}/follow:
    put:
      tags:
      - user-rest-controller
      summary: Current user follows another user by its username
      operationId: follow
      parameters:
      - name: username
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: User found and followed/unfollowed state changed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        "404":
          description: User not found
        "403":
          description: Current user not logged in
  /api/users/{userId}:
    put:
      tags:
      - user-rest-controller
      summary: Edit user by id
      operationId: userOperation
      parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: operation
        in: query
        required: true
        schema:
          type: string
      responses:
        "403":
          description: Admin access required
        "200":
          description: User found and banned/unbanned state changed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        "404":
          description: User not found
        "400":
          description: Operation doesn't exist
  /api/posts/upvotes/{postId}:
    put:
      tags:
      - post-rest-controller
      summary: Current user upvote a post
      operationId: upvotePost
      parameters:
      - name: postId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "404":
          description: Post not found
        "200":
          description: User found and upvoted the post
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        "403":
          description: Current user not logged in
  /api/posts/downvotes/{postId}:
    put:
      tags:
      - post-rest-controller
      summary: Current user downvote a post
      operationId: downvotePost
      parameters:
      - name: postId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "404":
          description: Post not found
        "200":
          description: User found and downvoted the post
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        "403":
          description: Current user not logged in
  /api/topics/:
    post:
      tags:
      - topic-rest-controller
      summary: Create topic
      operationId: createTopic
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Data'
        required: true
      responses:
        "201":
          description: Topic created
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Topic'
        "409":
          description: The name chose is already taken
        "403":
          description: Create topic only for admin
  /api/posts/:
    post:
      tags:
      - post-rest-controller
      summary: Create new post
      operationId: createPost
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Data'
        required: true
      responses:
        "201":
          description: Post created
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
        "403":
          description: Can't create post if not registered
        "400":
          description: Bad formatting
  /api/comments/{postId}:
    post:
      tags:
      - comment-rest-controller
      summary: Delete a comment of a post
      operationId: createComment
      parameters:
      - name: postId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Data'
        required: true
      responses:
        "201":
          description: Comment added
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Comment'
        "403":
          description: Can´t comment if not registered
  /api/auth/sign-out:
    post:
      tags:
      - auth-rest-controller
      summary: Sign-out user
      operationId: logOut
      responses:
        "200":
          description: Sign-out successful
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/AuthResponse'
  /api/auth/sign-in:
    post:
      tags:
      - auth-rest-controller
      summary: Sign-in user with credentials
      operationId: login
      parameters:
      - name: accessToken
        in: cookie
        required: false
        schema:
          type: string
      - name: refreshToken
        in: cookie
        required: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
        required: true
      responses:
        "403":
          description: Sign-in unsuccessful
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/AuthResponse'
        "200":
          description: Sign-in successful
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/AuthResponse'
  /api/auth/register:
    post:
      tags:
      - auth-rest-controller
      summary: Register a new user
      operationId: register
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegistrationRequest'
        required: true
      responses:
        "403":
          description: Username already taken
        "201":
          description: User created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        "400":
          description: Username/password is shorter than 4 characters or invalid email
            address
  /api/users/{username}:
    get:
      tags:
      - user-rest-controller
      summary: Get a user by its username
      operationId: getUser
      parameters:
      - name: username
        in: path
        required: true
        schema:
          type: string
      responses:
        "404":
          description: User not found
        "200":
          description: User found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  /api/users/{username}/following:
    get:
      tags:
      - user-rest-controller
      summary: Profile user following
      operationId: following
      parameters:
      - name: username
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: User found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Follow'
        "404":
          description: User not found
        "400":
          description: User logged in but not found
  /api/users/{username}/followers:
    get:
      tags:
      - user-rest-controller
      summary: Profile user followers
      operationId: followers
      parameters:
      - name: username
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: User found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Follow'
        "404":
          description: User not found
        "400":
          description: User logged in but not found
  /api/users/names/{prefix}:
    get:
      tags:
      - user-rest-controller
      operationId: getUserByPrefix
      parameters:
      - name: prefix
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
  /api/topics/{topicId}:
    get:
      tags:
      - topic-rest-controller
      summary: Get specific topic
      operationId: getTopic
      parameters:
      - name: topicId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "404":
          description: Topic not found
        "200":
          description: Topic found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Topic'
    delete:
      tags:
      - topic-rest-controller
      summary: Delete specific topic
      operationId: deleteTopic
      parameters:
      - name: topicId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "404":
          description: Topic not found
        "200":
          description: Topic deleted
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Topic'
        "403":
          description: Delete topic only for admin
  /api/topics/chart:
    get:
      tags:
      - topic-rest-controller
      operationId: getMappedTopics
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: integer
                  format: int32
  /api/topics/byName/{topicName}:
    get:
      tags:
      - topic-rest-controller
      summary: Get specific topic
      operationId: getTopicByName
      parameters:
      - name: topicName
        in: path
        required: true
        schema:
          type: string
      responses:
        "404":
          description: Topic not found
        "200":
          description: Topic found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Topic'
    delete:
      tags:
      - topic-rest-controller
      summary: Delete specific topic
      operationId: deleteTopic_1
      parameters:
      - name: topicName
        in: path
        required: true
        schema:
          type: string
      responses:
        "404":
          description: Topic not found
        "200":
          description: Topic deleted
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Topic'
        "403":
          description: Delete topic only for admin
  /api/posts:
    get:
      tags:
      - ajax-rest-controller
      summary: Load more posts
      operationId: getNewPosts
      parameters:
      - name: page
        in: query
        required: true
        schema:
          type: integer
          format: int32
      - name: filter
        in: query
        required: false
        schema:
          type: boolean
      responses:
        "200":
          description: New posts loaded
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
        "404":
          description: No new posts found
  /api/posts/{postId}:
    get:
      tags:
      - post-rest-controller
      summary: Get specific post
      operationId: getPost
      parameters:
      - name: postId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: Post found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
        "404":
          description: Post not found
    delete:
      tags:
      - post-rest-controller
      summary: Delete specific post
      operationId: deletePost
      parameters:
      - name: postId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "404":
          description: Post not found
        "200":
          description: Post deleted
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
        "403":
          description: Can't delete other one post
  /api/posts/images/{id}:
    get:
      tags:
      - post-rest-controller
      operationId: downloadImage
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
  /api/comments/user/{userId}:
    get:
      tags:
      - comment-rest-controller
      summary: Get all the comments of an user
      operationId: getUserComments
      parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "404":
          description: User not found
        "200":
          description: User found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Comment'
  /api/comments/posts/{postId}:
    get:
      tags:
      - comment-rest-controller
      summary: Get all the comments of a post
      operationId: getPostComments
      parameters:
      - name: postId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "404":
          description: Post not found
        "200":
          description: Post found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Comment'
  /api/auth/logged-user:
    get:
      tags:
      - auth-rest-controller
      summary: Get logged user
      operationId: userLogged
      responses:
        "404":
          description: User not found
        "200":
          description: User found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        "500":
          description: No user logged in
  /api/comments/{postId}/{commentId}:
    delete:
      tags:
      - comment-rest-controller
      summary: Delete a comment of a post
      operationId: deleteComment
      parameters:
      - name: postId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: commentId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "403":
          description: Can´t delete other one comment
        "404":
          description: Post or comment not found
        "200":
          description: Comment deleted
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Comment'
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        password:
          type: string
          writeOnly: true
        '@Id':
          type: integer
          format: int32
    Data:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
    Post:
      type: object
      properties:
        id:
          type: integer
          format: int64
        author:
          $ref: '#/components/schemas/User'
        date:
          type: string
          format: date-time
        title:
          type: string
        upVotesUsernames:
          uniqueItems: true
          type: array
          items:
            type: string
        downVotesUsernames:
          uniqueItems: true
          type: array
          items:
            type: string
        numUpvotes:
          type: integer
          format: int32
        numDownvotes:
          type: integer
          format: int32
        topicNames:
          type: array
          items:
            type: string
        items:
          type: array
          items:
            $ref: '#/components/schemas/PostItem'
        '@Id':
          type: integer
          format: int32
    PostItem:
      type: object
      properties:
        id:
          type: integer
          format: int64
        description:
          type: string
        imageFile:
          type: object
          properties:
            binaryStream:
              type: object
          writeOnly: true
        '@Id':
          type: integer
          format: int32
    Topic:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        posts:
          type: array
          items:
            $ref: '#/components/schemas/Post'
        '@Id':
          type: integer
          format: int32
    Comment:
      type: object
      properties:
        id:
          type: integer
          format: int64
        author:
          $ref: '#/components/schemas/User'
        date:
          type: string
          format: date-time
        content:
          type: string
        imagePath:
          type: string
        '@Id':
          type: integer
          format: int32
    AuthResponse:
      type: object
      properties:
        status:
          type: string
          enum:
          - SUCCESS
          - FAILURE
        message:
          type: string
        error:
          type: string
    LoginRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
    RegistrationRequest:
      type: object
      properties:
        username:
          type: string
        email:
          type: string
        password:
          type: string
    Follow:
      type: object
      properties:
        count:
          type: integer
          format: int32
        users:
          type: array
          items:
            $ref: '#/components/schemas/FollowUser'
    FollowUser:
      type: object
      properties:
        username:
          type: string
        follow:
          type: boolean
